basePath: /api/v1
definitions:
  config.OrderRequest:
    properties:
      OrderQuantity:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: anarm717@gmail.com
    name: API Support
  description: This is a sample service for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: OrderPackSizes API
  version: "1.0"
paths:
  /calculate-packs:
    post:
      consumes:
      - application/json
      description: Calculate pack sizes quantity
      parameters:
      - description: Calculate packs
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/config.OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Calculate pack sizes by quantity
      tags:
      - packs
  /pack-sizes:
    get:
      consumes:
      - application/json
      description: Get pack sizes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Get pack sizes
      tags:
      - packs
    post:
      consumes:
      - application/json
      description: Update pack sizes
      parameters:
      - description: Update pack sizes
        in: body
        name: tags
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Update pack sizes
      tags:
      - packs
swagger: "2.0"
